services:
  tellulf:
    image: ghcr.io/kvasbo/tellulf-v9:main
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "${EXPOSE_PORT}:3000"
    environment:
      - CAL_ID_FELLES=${CAL_ID_FELLES}
      - CAL_ID_BURSDAG=${CAL_ID_BURSDAG}
      - CAL_ID_MIDDAG=${CAL_ID_MIDDAG}
      - GOOGLE_KEY_B64=${GOOGLE_KEY_B64}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - DATABASE_URL=${DATABASE_URL}
      - TIBBER_KEY=${TIBBER_KEY}
      - TIBBER_ID_HOME=${TIBBER_ID_HOME}
      - TIBBER_ID_CABIN=${TIBBER_ID_CABIN}
networks:
  default:
    name: ${NETWORK_NAME}
    external: true
